# shareit-gateway/src/main/resources/application-docker.properties

server.port=8080
spring.application.name=shareit-gateway

# URL ??????? (????? Docker)
shareit-server.url=http://server:9090

logging.level.ru.practicum.shareit=DEBUG